name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Restore
        run: dotnet restore FactoryGenerator.sln
      - name: Build
        run: dotnet build FactoryGenerator.sln --no-restore
      - name: Test
        run: dotnet test FactoryGenerator.sln --no-build --no-restore

  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: |
          If (('${{ github.event_name }}' -eq 'release') -and ('${{ github.ref_name }}' -match '^(?<version>\d+\.\d+\.\d+)')) {
            Add-Content -Path $Env:GITHUB_ENV -Value "VERSION=$($Matches.version)"
            Add-Content -Path $Env:GITHUB_ENV -Value "FILE_VERSION=$($Matches.version).0"
            Add-Content -Path $Env:GITHUB_ENV -Value "INFORMAL_VERSION=${{ github.ref_name }}"
          } else {
            Add-Content -Path $Env:GITHUB_ENV -Value "VERSION=0.0.0"
            Add-Content -Path $Env:GITHUB_ENV -Value "FILE_VERSION=0.0.0.0"
            Add-Content -Path $Env:GITHUB_ENV -Value "INFORMAL_VERSION=UNRELEASED"
          }
        name: "Set package version meta data"
      - name: Pack Generator
        run: dotnet pack FactoryGenerator/FactoryGenerator.csproj -o "${{ env.NuGetDirectory }}"
      - name: Pack Attributes
        run: dotnet pack FactoryGenerator.Attributes/FactoryGenerator.Attributes.csproj -o "${{ env.NuGetDirectory }}" --property:RepositoryCommit="${{ env.COMMIT_SHA }}" --property:InformationalVersion="${{ env.INFORMAL_VERSION }}" --property:AssemblyVersion="${{ env.VERSION }}" --property:FileVersion="${{ env.VERSION }}" --property:Version="${{ env.VERSION }}"
      - uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          if-no-files-found: error
          retention-days: 1
          path: ${{ env.NuGetDirectory }}/*.nupkg

  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [pack]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ${{ env.NuGetDirectory }}
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
      - name: Publish Nuget packages
        run: |
          for file in $(find "${{ env.NuGetDirectory }}" -type f -name "*.nupkg"); do
            dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
          done
